# spec:
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2
env:
  variables:
    TZ: "America/New_York date"
    # The remote origin that will be used if building through CodePipeline
    remote_origin: "git@github.com:cwcrypto/thoum.git"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Install started on `date`
      - npm i
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Run unit tests started on `date`
      - echo "Running thoum Unit Tests"
      - npm run test