export const enum DAEMON_EXIT_CODES {
    UNSPECIFIED_ERROR               = 1,
    DAEMON_PANIC                    = 2,
    CANCELLED_BY_USER               = 3,
    USER_NOT_FOUND                  = 4,
    ZLI_CONFIG_ERROR                = 5,
    SERVICE_ACCOUNT_NOT_CONFIGURED  = 6,
    POLICY_EDITED_DISCONNECT        = 7,
    POLICY_DELETED_DISCONNECT       = 8,
    IDLE_TIMEOUT                    = 9,
    CONNECTION_REFUSED              = 10,
    CONNECTION_FAILED               = 11,
    DB_NO_TLS                       = 12,
    CLIENT_CERT_COSIGN_ERROR        = 13,
    PWDB_MISSING_KEY                = 14,
    PWDB_UNKNOWN_AUTHORITY          = 15,
    SERVER_CERT_EXPIRED             = 16,
    INCORRECT_SERVER_NAME           = 17,
    BZCERT_ID_TOKEN_ERROR           = 18,
    FAILED_TO_START_126             = 126,
    FAILED_TO_START_127             = 127
}
