name: System Test Develop Branch CI -- Windows
on:
  pull_request:
    branches:
      # Run System Tests on PRs to develop or PRs to feature branches (should be based on develop)
      - develop
      - "feat/**"
jobs:
  hello:
    runs-on: [self-hosted, windows]
    name: Hello
    steps:
    - name: Say hello
      id: sayhello
      run: |
        echo hello